// Generated by CoffeeScript 1.6.3
var crypto;

crypto = require('crypto');

module.exports = {
  encrypt: function(text) {
    var cipher, crypted;
    cipher = crypto.createCipher("aes-256-cbc", "theBestSite!");
    crypted = cipher.update(text, "utf8", "hex");
    crypted += cipher.final("hex");
    return crypted;
  },
  decrypt: function(text) {
    var dec, decipher;
    decipher = crypto.createDecipher("aes-256-cbc", "theBestSite!");
    dec = decipher.update(text, "hex", "utf8");
    dec += decipher.final("utf8");
    return dec;
  },
  gui: function() {
    return Math.random().toString(36).substring(2);
  }
};
