// Generated by CoffeeScript 1.6.3
var Key, Main, bitcore, extend, http, key;

http = require('http');

bitcore = require('bitcore');

Key = require('./key');

key = new Key();

Main = (function() {
  var run, settings;

  settings = {
    network: bitcore.networks.livenet
  };

  function Main(address, o) {
    if (o == null) {
      o = {};
    }
    if (!address) {
      return 'must have address';
    }
    console.log('hello ' + address);
    settings = extend(settings, o);
    run();
  }

  run = function() {
    return key.createKeyPair({
      network: settings.network
    });
  };

  return Main;

})();

extend = function(object, properties) {
  var val;
  for (key in properties) {
    val = properties[key];
    object[key] = val;
  }
  return object;
};

module.exports = Main;
