// Generated by CoffeeScript 1.6.3
var Key, Main, bitcore, crypt, extend, fs, http;

http = require('http');

bitcore = require('bitcore');

crypt = require('./encrypt');

Key = require('./key');

fs = require('fs');

Main = (function() {
  var run, settings, store_keys;

  settings = {
    network: bitcore.networks.livenet,
    password: 'enter_your_password_here',
    storePath: './keys.json'
  };

  function Main(address, o) {
    if (o == null) {
      o = {};
    }
    if (!address) {
      return 'must have address';
    }
    console.log('hello ' + address);
    settings = extend(settings, o);
    run();
  }

  run = function() {
    var key;
    return key = new Key({
      network: settings.network,
      storePath: settings.storePath
    });
  };

  store_keys = function() {};

  return Main;

})();

extend = function(object, properties) {
  var key, val;
  for (key in properties) {
    val = properties[key];
    object[key] = val;
  }
  return object;
};

module.exports = Main;
